### ISSUE TITLE
applySchemaCustomDirectives cannot handle recursive nested objects

### ISSUE THREAD

**Issue by zeemi** [lirown/graphql-custom-directives#17]
As far as i was able to debug - wrapping fields with middleware from `applySchemaCustomDirectives` cannot be handled when object has recursion to itself in nested fields.

error:
```
RangeError: Maximum call stack size exceeded
at wrapFieldsWithMiddleware (.../node_modules/graphql-custom-directives/dist/custom.js:166:34)
at wrapFieldsWithMiddleware (.../node_modules/graphql-custom-directives/dist/custom.js:184:11)
at wrapFieldsWithMiddleware (.../node_modules/graphql-custom-directives/dist/custom.js:184:11)
at wrapFieldsWithMiddleware (.../node_modules/graphql-custom-directives/dist/custom.js:184:11)
at wrapFieldsWithMiddleware (.../node_modules/graphql-custom-directives/dist/custom.js:184:11)
at wrapFieldsWithMiddleware (.../node_modules/graphql-custom-directives/dist/custom.js:184:11)
at wrapFieldsWithMiddleware (.../node_modules/graphql-custom-directives/dist/custom.js:184:11)
at wrapFieldsWithMiddleware (.../node_modules/graphql-custom-directives/dist/custom.js:184:11)
at wrapFieldsWithMiddleware (.../node_modules/graphql-custom-directives/dist/custom.js:184:11)
at wrapFieldsWithMiddleware (.../node_modules/graphql-custom-directives/dist/custom.js:184:11)
[nodemon] app crashed - waiting for file changes before starting...
```

example of nested object (children field):
```
export const ExampleObjectType = new GraphQLObjectType({
  name: 'ExampleObject',
  fields: () => ({
    name: {type: GraphQLString},
    url: {type: GraphQLString},
    target: {type: GraphQLString},
    children: {
      type: new GraphQLList(ExampleObjectType)
    },
  })
});
```

**Comment by lirown** [comment]
Fixed
